### ISSUE TITLE
Timeouts When Writing to Slave

### ISSUE THREAD

**Issue by stevehayenergy** [rmodbus/rmodbus#55] opened 2018-04-26 15:52 UTC
I am getting timeouts when writing to a slave very aggressively. I have 30 or so threads all writing values to the same register, and the rmodbus slave very reliably times out. I think there is probably a need for a Mutex somewhere, because I think the io streams are stepping on each other.

If I slow down the sequence of writes, it gets more reliable. I think the problem occurs when more than one connection is writing to the slave at the time time. This happens whether the threads are writing to the same register or different registers.

**Comment by fernandoluizao** [comment] 2018-04-27 11:00
Which protocol are you using? I will review the code to find possible solutions.

**Comment by fernandoluizao** [comment] 2018-05-10 20:02
Sorry for the delay, I've been a little busy with another project.

Could you try the **mutex** branch to see if the problem has been solved? If you can, please make some benchmarks, and let me know if there was an impact on the performance.

**Comment by jhadeepakkumar14** [comment] 2018-08-29 07:53
I am also facing the same issue.

**Comment by fernandoluizao** [comment] 2018-08-29 10:50
@jhadeepakkumar14 can you try with [this](https://github.com/rmodbus/rmodbus/tree/mutex) branch please?

**Comment by ccutrer** [comment] 2024-08-20 15:50
This is a duplicate of #16.

**Closed by ccutrer** 2024-08-20 15:50 UTC
